#!/bin/bash

# Author: Vladyslav Hrynchuk
# Date created 4/1/2022
# Last Modofied 4/1/2022

# Desription:
# Prints to the terminal

# Usage
# our_first_script

# Prints to the output

echo "this is my first script"
exit 0
