#!/bin/bash

read -p "What is your first name: " first_name 
read -p "What is your surname: " surname
PS3="Please choose between headset and handset: "
select phone in headset handset
do
break
done
PS3="Please enter your department: "
select department in finance sales "customer service" engineering
do
break
done
read -N 4 -p "What is your extension number: " extension_number
echo " "
read -N 4 -p "What acces code would you like to use when dialing in: " -s  access_code
echo " "
echo "$first_name,$surname,$extension_number,$access_code,$phone,$department" >> extensions.csv
