#!/bin/bash

# Author: Vladyslav Hrynchuk
# Date created: 4/1/22
# Last modified: 5/1/22

# Description:
# This is a script for backing up your home folder data to current working directory

# Usage: ./backup_script

currentdir=$(pwd)

echo "Hello, ${USER^}"
echo "I will now back up your home directory $HOME"
echo "you are running this script from $currentdir"
echo "therefore, I will save the backup in $currentdir"

tar -cf $currentdir/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null
echo "backup completed suceesfully"
exit 0
